use super::RestState;
use std::net::SocketAddr;
use std::time::Duration;
use tower_http::cors::{Any, CorsLayer};
use tower_http::normalize_path::NormalizePathLayer;

pub async fn serve(state: RestState, addr: SocketAddr) -> Result<(), std::io::Error> {
    let mw_state = state.clone();
    let shutdown_state = state.clone();

    // NOTE: The actual route handlers remain in the parent module (`rest.rs`) for now.
    // This file extracts only the router wiring and server lifecycle to de-monolith the module.
    //
    // Layer order (last `.layer` = **outermost**; runs first on incoming requests):
    //   Cors → default body limit → global rate limit → routes.
    // CORS must stay outermost so preflight and `Access-Control-*` apply before auth/rate-limit.
    let app = axum::Router::new()
        .route("/", axum::routing::get(super::handlers::pages::get_index))
        // Marketing home (/) is strictly separated from the operator app (/app).
        .route(
            "/app",
            axum::routing::get(super::handlers::pages::get_worker_app),
        )
        // Keep the legacy core UI accessible at a non-root path.
        .route("/core", axum::routing::get(super::handlers::ui::get_ui))
        .route(
            "/logs",
            axum::routing::get(super::handlers::logs::get_logs_sse),
        )
        .route(
            "/execute",
            axum::routing::post(super::handlers::logs::post_execute),
        )
        // Back-compat for old deep links from early builds.
        .route(
            "/worker_dashboard.html",
            axum::routing::get(super::handlers::pages::get_worker_app_redirect),
        )
        .route(
            "/founder",
            axum::routing::get(super::handlers::pages::get_founder_terminal),
        )
        .route(
            "/assets/founder_terminal.js",
            axum::routing::get(super::handlers::assets::get_founder_terminal_js),
        )
        .route(
            "/assets/wallet_client_bundled.js",
            axum::routing::get(super::handlers::assets::get_wallet_client_bundled_js),
        )
        .route(
            "/assets/landing.js",
            axum::routing::get(super::handlers::assets::get_landing_js),
        )
        .route(
            "/assets/ui.js",
            axum::routing::get(super::handlers::assets::get_ui_js),
        )
        .route(
            "/assets/nexus_wasm.js",
            axum::routing::get(super::handlers::ui::get_nexus_wasm_js),
        )
        .route(
            "/assets/nexus_wasm_bg.wasm",
            axum::routing::get(super::handlers::ui::get_nexus_wasm_bg_wasm),
        )
        .route(
            "/assets/tet_sdk.js",
            axum::routing::get(super::handlers::assets::get_tet_sdk_js),
        )
        .route(
            "/assets/tet_sdk_node.mjs",
            axum::routing::get(super::handlers::assets::get_tet_sdk_node_mjs),
        )
        .route(
            "/status",
            axum::routing::get(super::handlers::pages::get_status),
        )
        .route(
            "/logout",
            axum::routing::post(super::handlers::pages::post_logout),
        )
        .route(
            "/telemetry/local",
            axum::routing::get(super::handlers::telemetry::get_local_telemetry),
        )
        .route(
            "/metrics",
            axum::routing::get(super::handlers::metrics::get_metrics),
        )
        .route(
            "/wallet/mnemonic/new",
            axum::routing::get(super::handlers::wallet::get_wallet_mnemonic_new)
                .post(super::handlers::wallet::post_wallet_new),
        )
        .route(
            "/wallet/mnemonic/recover",
            axum::routing::post(super::handlers::wallet::post_wallet_recover),
        )
        .route(
            "/wallet/active",
            axum::routing::post(super::handlers::wallet::post_wallet_set_active),
        )
        .route(
            "/wallet/nonce/:wallet",
            axum::routing::get(super::handlers::wallet::get_wallet_transfer_nonce),
        )
        .route(
            "/wallet/transfer",
            axum::routing::post(super::handlers::wallet::post_wallet_transfer),
        )
        .route(
            "/wallet/stake",
            axum::routing::post(super::handlers::wallet::post_wallet_stake),
        )
        .route(
            "/wallet/slash",
            axum::routing::post(super::handlers::wallet::post_wallet_slash),
        )
        .route(
            "/signer/link",
            axum::routing::post(super::handlers::wallet::post_signer_link),
        )
        .route(
            "/founding/enroll",
            axum::routing::post(super::handlers::founding::post_founding_enroll),
        )
        .route(
            "/founding/cert/:wallet",
            axum::routing::get(super::handlers::founding::get_founding_cert),
        )
        .route(
            "/ledger/me",
            axum::routing::get(super::handlers::ledger::get_ledger_me),
        )
        .route(
            "/ledger/state",
            axum::routing::get(super::handlers::ledger::get_ledger_state),
        )
        .route(
            "/ledger/blocks",
            axum::routing::get(super::handlers::ledger::get_ledger_blocks),
        )
        .route(
            "/ledger/block/:height",
            axum::routing::get(super::handlers::ledger::get_ledger_block),
        )
        .route(
            "/genesis/1000/status",
            axum::routing::get(super::handlers::ledger::get_genesis_1k_status),
        )
        .route(
            "/genesis/1000/claim",
            axum::routing::post(super::handlers::ledger::post_genesis_1k_claim),
        )
        .route(
            "/ledger/initial_airdrop/claim",
            axum::routing::post(super::handlers::ledger::post_initial_airdrop_claim),
        )
        .route(
            "/ledger/balance/:wallet",
            axum::routing::get(super::handlers::ledger::get_ledger_balance),
        )
        .route(
            "/ledger/stake",
            axum::routing::post(super::handlers::ledger::post_ledger_stake),
        )
        .route(
            "/ledger/unstake",
            axum::routing::post(super::handlers::ledger::post_ledger_unstake),
        )
        .route(
            "/ledger/transfer",
            axum::routing::post(super::handlers::ledger::post_transfer_enveloped),
        )
        .route(
            "/ledger/mine",
            axum::routing::post(super::handlers::ledger::post_ledger_mine),
        )
        .route(
            "/ledger/zk_verify",
            axum::routing::post(super::handlers::ledger::post_ledger_zk_verify),
        )
        .route(
            "/ledger/mint_demo",
            axum::routing::post(super::handlers::ledger::post_mint_demo),
        )
        .route(
            "/ledger/faucet",
            axum::routing::post(super::handlers::ledger::post_ledger_faucet),
        )
        // Dev alias (same handler as `/ledger/faucet`): admin Bearer mint from worker pool.
        .route(
            "/faucet",
            axum::routing::post(super::handlers::ledger::post_ledger_faucet),
        )
        .route(
            "/ledger/proof",
            axum::routing::get(super::handlers::ledger::get_proofs),
        )
        .route(
            "/ledger/proof/:id",
            axum::routing::get(super::handlers::ledger::get_proof_by_id),
        )
        .route(
            "/ledger/genesis_bridge",
            axum::routing::post(super::handlers::ledger::post_genesis_bridge_enveloped),
        )
        .route(
            "/tx/submit",
            axum::routing::post(super::handlers::ledger::post_tx_submit),
        )
        .route(
            "/ai/pricing",
            axum::routing::get(super::handlers::ai::get_ai_pricing),
        )
        .route(
            "/ai/proxy",
            axum::routing::post(super::handlers::ai::post_ai_proxy),
        )
        .route(
            "/ai/utility",
            axum::routing::post(super::handlers::ai::post_ai_utility),
        )
        .route(
            "/ai/infer",
            axum::routing::post(super::handlers::ai::post_ai_infer),
        )
        .route(
            "/ai/history/:wallet",
            axum::routing::get(super::handlers::ai::get_ai_infer_history),
        )
        .route(
            "/ai/nonce",
            axum::routing::get(super::handlers::ai::get_ai_nonce),
        )
        .route(
            "/ai/infer_signed",
            axum::routing::post(super::handlers::ai::post_ai_infer_signed),
        )
        .route(
            "/explorer/events",
            axum::routing::get(super::handlers::ledger::get_explorer_events),
        )
        .route(
            "/explorer/tx/:hash",
            axum::routing::get(super::handlers::ledger::get_explorer_tx),
        )
        .route(
            "/vault/history",
            axum::routing::get(super::handlers::ledger::get_vault_history),
        )
        .route(
            "/market/index",
            axum::routing::get(super::handlers::ledger::get_market_index),
        )
        // Compatibility alias for automation scripts / clients.
        .route(
            "/api/v1/ai/utility",
            axum::routing::post(super::handlers::ai::post_ai_utility),
        )
        .route(
            "/enterprise/inference",
            axum::routing::post(super::handlers::enterprise::post_enterprise_inference),
        )
        .route(
            "/enterprise/inference/submit",
            axum::routing::post(super::handlers::enterprise::post_enterprise_inference_submit),
        )
        .route(
            "/worker/register",
            axum::routing::post(super::handlers::worker::post_worker_register),
        )
        .route(
            "/worker/model/status",
            axum::routing::get(super::handlers::worker::get_worker_model_status),
        )
        .route(
            "/worker/model/download",
            axum::routing::post(super::handlers::worker::post_worker_model_download),
        )
        .route(
            "/worker/ai_engine/status",
            axum::routing::get(super::handlers::worker::get_worker_ai_engine_status),
        )
        .route(
            "/v1/compute_e2ee/submit",
            axum::routing::post(super::handlers::worker::post_v1_compute_e2ee_submit),
        )
        .route(
            "/v1/compute_e2ee/result/:job_id",
            axum::routing::get(super::handlers::worker::get_v1_compute_e2ee_result),
        )
        .route(
            "/worker/e2ee/next/:wallet",
            axum::routing::get(super::handlers::worker::get_worker_e2ee_next),
        )
        .route(
            "/worker/e2ee/complete",
            axum::routing::post(super::handlers::worker::post_worker_e2ee_complete),
        )
        .route(
            "/worker/stats/:wallet",
            axum::routing::get(super::handlers::worker::get_worker_stats),
        )
        .route(
            "/worker/cockpit/:wallet",
            axum::routing::get(super::handlers::worker::get_worker_cockpit),
        )
        .route(
            "/worker/pending/:wallet",
            axum::routing::get(super::handlers::worker::get_worker_pending),
        )
        .route(
            "/network/power",
            axum::routing::get(super::handlers::network::get_network_power),
        )
        .route(
            "/network/stats",
            axum::routing::get(super::handlers::network::get_network_stats),
        )
        .route(
            "/v1/compute",
            axum::routing::post(super::handlers::network::post_v1_compute),
        )
        // ---------------- Phase X: P2P DEX (Isolated) ----------------
        .route(
            "/dex/order/place",
            axum::routing::post(super::handlers::dex::post_dex_order_place),
        )
        .route(
            "/dex/order/cancel",
            axum::routing::post(super::handlers::dex::post_dex_order_cancel),
        )
        .route(
            "/dex/take",
            axum::routing::post(super::handlers::dex::post_dex_take),
        )
        .route(
            "/dex/trade/complete",
            axum::routing::post(super::handlers::dex::post_dex_trade_complete),
        )
        .route(
            "/dex/settlement/confirm",
            axum::routing::post(super::handlers::dex::post_dex_settlement_confirm),
        )
        .route(
            "/dex/sweep/refunds",
            axum::routing::post(super::handlers::dex::post_dex_sweep_refunds),
        )
        .route(
            "/dex/orderbook",
            axum::routing::get(super::handlers::dex::get_dex_orderbook),
        )
        .route(
            "/ledger/recover-from-guardian",
            axum::routing::post(super::handlers::ledger::post_ledger_recover_from_guardian),
        )
        .route(
            "/v1/b2b/compute",
            axum::routing::post(super::handlers::b2b::post_v1_b2b_compute),
        )
        .route(
            "/founder/audit.csv",
            axum::routing::get(super::handlers::founder::get_founder_audit_csv),
        )
        .route(
            "/founder/genesis",
            axum::routing::post(super::handlers::founder::post_founder_genesis),
        )
        .route(
            "/founder/withdraw_treasury",
            axum::routing::post(super::handlers::founder::post_founder_withdraw_treasury),
        )
        .route(
            "/system/update",
            axum::routing::get(super::handlers::system::get_system_update),
        )
        .route(
            "/admin/gossip",
            axum::routing::post(super::handlers::admin::post_admin_gossip),
        )
        .route(
            "/phase4/tee/status",
            axum::routing::get(super::handlers::phase4::get_phase4_tee_status),
        )
        .route(
            "/phase4/marketplace/status",
            axum::routing::get(super::handlers::phase4::get_phase4_marketplace_status),
        )
        .route(
            "/phase4/render-farm/status",
            axum::routing::get(super::handlers::phase4::get_phase4_render_farm_status),
        )
        // -------- Whitepaper Phase 0–2 vision scaffolding (REST probes) --------
        .route(
            "/v1/vision/caac/profile",
            axum::routing::get(super::handlers::vision::get_vision_caac_profile),
        )
        .route(
            "/v1/vision/caac/challenge",
            axum::routing::get(super::handlers::vision::get_vision_caac_challenge),
        )
        .route(
            "/v1/vision/caac/complete",
            axum::routing::post(super::handlers::vision::post_vision_caac_complete),
        )
        .route(
            "/v1/vision/caac/worker/:wallet",
            axum::routing::get(super::handlers::vision::get_vision_caac_worker),
        )
        .route(
            "/v1/vision/zk-court/verify-optimistic",
            axum::routing::post(super::handlers::vision::post_vision_zk_court_verify_optimistic),
        )
        .route(
            "/v1/vision/zk-court/params",
            axum::routing::get(super::handlers::vision::get_vision_zk_court_params),
        )
        .route(
            "/v1/vision/zk-court/challenges",
            axum::routing::get(super::handlers::vision::get_vision_zk_court_challenges),
        )
        .route(
            "/v1/vision/zk-court/challenge",
            axum::routing::post(super::handlers::vision::post_vision_zk_court_challenge),
        )
        .route(
            "/v1/vision/pqc/status",
            axum::routing::get(super::handlers::vision::get_vision_pqc_status),
        )
        .route(
            "/v1/vision/thermo/genesis",
            axum::routing::get(super::handlers::vision::get_vision_thermo_genesis),
        )
        .route(
            "/v1/vision/ai/infer/estimate",
            axum::routing::get(super::handlers::vision::get_vision_ai_infer_estimate),
        )
        .route(
            "/v1/vision/network/config",
            axum::routing::get(super::handlers::vision::get_vision_network_config),
        )
        // Vision-prefixed aliases (same handlers as top-level REST; stable paths for Sovereign OS).
        .route(
            "/v1/vision/ledger/me",
            axum::routing::get(super::handlers::ledger::get_ledger_me),
        )
        .route(
            "/v1/vision/ledger/initial_airdrop/claim",
            axum::routing::post(super::handlers::ledger::post_initial_airdrop_claim),
        )
        .route(
            "/v1/vision/market/index",
            axum::routing::get(super::handlers::ledger::get_market_index),
        )
        .route(
            "/v1/vision/network/stats",
            axum::routing::get(super::handlers::network::get_network_stats),
        )
        .with_state(state)
        // Trailing slash on paths (e.g. .../verify-optimistic/) → 404 without this.
        .layer(NormalizePathLayer::trim_trailing_slash())
        .layer(axum::extract::DefaultBodyLimit::max(2 * 1024 * 1024))
        .layer(axum::middleware::from_fn_with_state(
            mw_state,
            super::helpers::global_http_ratelimit,
        ))
        // Full cross-origin access for browser UIs (localhost:any, LAN demos, Sovereign OS).
        .layer(
            CorsLayer::new()
                .allow_origin(Any)
                .allow_methods(Any)
                .allow_headers(Any)
                .allow_private_network(true),
        );

    let listener = tokio::net::TcpListener::bind(addr).await?;
    axum::serve(
        listener,
        app.into_make_service_with_connect_info::<SocketAddr>(),
    )
    .with_graceful_shutdown(async move {
        // Graceful shutdown on SIGTERM/SIGINT/CTRL-C.
        #[cfg(unix)]
        {
            use tokio::signal::unix::{SignalKind, signal};
            let mut term = signal(SignalKind::terminate()).ok();
            let mut int = signal(SignalKind::interrupt()).ok();
            tokio::select! {
                _ = tokio::signal::ctrl_c() => {},
                _ = async { if let Some(s) = term.as_mut() { let _ = s.recv().await; } } => {},
                _ = async { if let Some(s) = int.as_mut() { let _ = s.recv().await; } } => {},
            }
        }
        #[cfg(not(unix))]
        {
            let _ = tokio::signal::ctrl_c().await;
        }
        eprintln!("[SHUTDOWN] Signal received. Flushing ledger…");
        shutdown_state.ledger.flush_and_snapshot_best_effort();
        // Give IO a moment; this is best-effort.
        tokio::time::sleep(Duration::from_millis(250)).await;
    })
    .await
}
